// React Full Curriculum
const DATA_REACT = {
id:'react', name:'React', icon:'⚛️', color:'#61DAFB',
gradient:'linear-gradient(135deg,#61DAFB,#282C34)',
category:'frontend',
description:'UI library, SPA, component-based, Next.js, React Native',
levels:[
  {id:'newbie',name:'Newbie',badge:'newbie',desc:'JSX, Components & Props',lessons:[
    {id:'intro',title:'JSX & Components cơ bản',
     theory:'<p><strong>React</strong> dùng <code>JSX</code> — HTML-like syntax trong JavaScript. Mọi UI là <strong>component</strong> — hàm trả về JSX. Components tái sử dụng, compose được.</p>',
     code:'// Function component\nfunction Greeting({ name, emoji = "👋" }) {\n  return (\n    <div className="greeting">\n      <h1>{emoji} Hello, {name}!</h1>\n      <p>Welcome to React</p>\n    </div>\n  );\n}\n\n// Component composition\nfunction App() {\n  return (\n    <div>\n      <Greeting name="An" />\n      <Greeting name="Binh" emoji="🎉" />\n    </div>\n  );\n}\n\nexport default App;',
     lang:'javascript',
     keyPoints:['JSX = JavaScript + HTML, className thay class','Component = function trả về JSX','Props: truyền data từ parent → child'],
     exercise:'Tạo component Card hiển thị ảnh, title, description.'},

    {id:'props-events',title:'Props, Events & Conditional Rendering',
     theory:'<p><strong>Props</strong> truyền data xuống, <strong>events</strong> gửi actions lên. <code>onClick, onChange, onSubmit</code> là event handlers. Conditional rendering dùng <code>&&</code>, ternary, hoặc early return.</p>',
     code:'function TodoItem({ todo, onToggle, onDelete }) {\n  return (\n    <li className={todo.done ? "done" : ""}>\n      <input\n        type="checkbox"\n        checked={todo.done}\n        onChange={() => onToggle(todo.id)}\n      />\n      <span>{todo.title}</span>\n      {!todo.done && (\n        <button onClick={() => onDelete(todo.id)}>🗑️</button>\n      )}\n    </li>\n  );\n}\n\nfunction TodoList() {\n  const todos = [\n    { id: 1, title: "Learn React", done: true },\n    { id: 2, title: "Build Project", done: false },\n  ];\n\n  return (\n    <ul>\n      {todos.length === 0\n        ? <p>No todos!</p>\n        : todos.map(todo => (\n            <TodoItem\n              key={todo.id}\n              todo={todo}\n              onToggle={id => console.log("toggle", id)}\n              onDelete={id => console.log("delete", id)}\n            />\n          ))\n      }\n    </ul>\n  );\n}',
     lang:'javascript',
     keyPoints:['Events: onClick={() => fn()} truyền handler qua props','key={unique} BẮT BUỘC khi render list','Conditional: {show && <Comp/>} hoặc ternary'],
     exercise:'Tạo component FilterableList với search input và filtered results.'},

    {id:'lists-keys',title:'Lists, Keys & Children Pattern',
     theory:'<p>React render lists với <code>.map()</code>. <strong>key</strong> giúp React track elements hiệu quả. <code>children</code> prop cho component composition. Fragment (<code><></code>) nhóm elements không thêm DOM node.</p>',
     code:'// Reusable Layout with children\nfunction Card({ title, children, footer }) {\n  return (\n    <div className="card">\n      <div className="card-header">\n        <h3>{title}</h3>\n      </div>\n      <div className="card-body">{children}</div>\n      {footer && <div className="card-footer">{footer}</div>}\n    </div>\n  );\n}\n\n// Render list with proper keys\nfunction UserList({ users }) {\n  if (users.length === 0) {\n    return <p className="empty">No users found</p>;\n  }\n  return (\n    <>\n      <h2>Users ({users.length})</h2>\n      <div className="user-grid">\n        {users.map(user => (\n          <Card\n            key={user.id}\n            title={user.name}\n            footer={<span>Joined: {user.joinDate}</span>}\n          >\n            <p>Email: {user.email}</p>\n            <p>Role: {user.role}</p>\n          </Card>\n        ))}\n      </div>\n    </>\n  );\n}',
     lang:'javascript',
     keyPoints:['key={id} dùng unique ID, KHÔNG dùng index','children prop cho flexible component composition','<></> Fragment nhóm elements không thêm wrapper div'],
     exercise:'Tạo reusable Table component nhận columns config và data array.'}
  ]},

  {id:'junior',name:'Junior',badge:'junior',desc:'Hooks & State Management',lessons:[
    {id:'hooks',title:'useState & useEffect',
     theory:'<p><code>useState</code> quản lý component state. <code>useEffect</code> cho side effects (API calls, timers, subscriptions). Dependency array kiểm soát khi nào effect chạy.</p>',
     code:'import { useState, useEffect } from "react";\n\nfunction Timer() {\n  const [seconds, setSeconds] = useState(0);\n  const [isRunning, setIsRunning] = useState(false);\n\n  useEffect(() => {\n    if (!isRunning) return;\n    const interval = setInterval(() => {\n      setSeconds(s => s + 1);\n    }, 1000);\n    return () => clearInterval(interval); // cleanup!\n  }, [isRunning]);\n\n  return (\n    <div>\n      <h1>{seconds}s</h1>\n      <button onClick={() => setIsRunning(!isRunning)}>\n        {isRunning ? "Pause" : "Start"}\n      </button>\n      <button onClick={() => { setSeconds(0); setIsRunning(false); }}>\n        Reset\n      </button>\n    </div>\n  );\n}\n\nfunction UserSearch() {\n  const [query, setQuery] = useState("");\n  const [users, setUsers] = useState([]);\n  const [loading, setLoading] = useState(false);\n\n  useEffect(() => {\n    if (!query) { setUsers([]); return; }\n    const controller = new AbortController();\n    setLoading(true);\n    fetch(`/api/users?q=${query}`, { signal: controller.signal })\n      .then(r => r.json())\n      .then(data => setUsers(data))\n      .finally(() => setLoading(false));\n    return () => controller.abort(); // cancel on change\n  }, [query]);\n}',
     lang:'javascript',
     keyPoints:['useState: setX(newVal) hoặc setX(prev => prev + 1)','useEffect return cleanup function (unmount/re-run)','Dependency array: [] chạy 1 lần, [dep] chạy khi dep thay đổi'],
     exercise:'Tạo component fetch API với loading, error, retry states.'},

    {id:'forms',title:'Forms & Controlled Components',
     theory:'<p>React dùng <strong>controlled components</strong>: state quản lý form values. <code>onChange</code> cập nhật state, <code>value</code> bind state → input. Custom validation logic.</p>',
     code:'import { useState } from "react";\n\nfunction RegisterForm({ onSubmit }) {\n  const [form, setForm] = useState({\n    name: "", email: "", password: ""\n  });\n  const [errors, setErrors] = useState({});\n\n  const validate = () => {\n    const newErrors = {};\n    if (!form.name.trim()) newErrors.name = "Name required";\n    if (!/\\S+@\\S+\\.\\S+/.test(form.email))\n      newErrors.email = "Invalid email";\n    if (form.password.length < 8)\n      newErrors.password = "Min 8 characters";\n    setErrors(newErrors);\n    return Object.keys(newErrors).length === 0;\n  };\n\n  const handleChange = (e) => {\n    const { name, value } = e.target;\n    setForm(prev => ({ ...prev, [name]: value }));\n    setErrors(prev => ({ ...prev, [name]: "" }));\n  };\n\n  const handleSubmit = (e) => {\n    e.preventDefault();\n    if (validate()) onSubmit(form);\n  };\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input name="name" value={form.name}\n        onChange={handleChange} placeholder="Name" />\n      {errors.name && <span className="error">{errors.name}</span>}\n\n      <input name="email" value={form.email}\n        onChange={handleChange} placeholder="Email" />\n      {errors.email && <span className="error">{errors.email}</span>}\n\n      <input name="password" type="password"\n        value={form.password} onChange={handleChange} />\n      {errors.password && <span className="error">{errors.password}</span>}\n\n      <button type="submit">Register</button>\n    </form>\n  );\n}',
     lang:'javascript',
     keyPoints:['Controlled: value={state} + onChange={setState}','e.preventDefault() ngăn form reload page','Spread: setForm(prev => ({...prev, [name]: value}))'],
     exercise:'Tạo multi-step form wizard với validation mỗi step.'},

    {id:'routing',title:'React Router & Navigation',
     theory:'<p><code>React Router</code> cho client-side routing (SPA). <code>Routes</code>, <code>Link</code>, <code>useNavigate</code>, <code>useParams</code>. Nested routes, protected routes, lazy loading.</p>',
     code:'import { BrowserRouter, Routes, Route, Link,\n  useParams, useNavigate, Navigate } from "react-router-dom";\nimport { lazy, Suspense } from "react";\n\nconst Dashboard = lazy(() => import("./Dashboard"));\n\nfunction ProtectedRoute({ children }) {\n  const isAuth = localStorage.getItem("token");\n  return isAuth ? children : <Navigate to="/login" />;\n}\n\nfunction UserProfile() {\n  const { id } = useParams();\n  const navigate = useNavigate();\n  return (\n    <div>\n      <h2>User {id}</h2>\n      <button onClick={() => navigate(-1)}>Back</button>\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <nav>\n        <Link to="/">Home</Link>\n        <Link to="/users">Users</Link>\n      </nav>\n      <Suspense fallback={<div>Loading...</div>}>\n        <Routes>\n          <Route path="/" element={<Home />} />\n          <Route path="/users/:id" element={<UserProfile />} />\n          <Route path="/dashboard" element={\n            <ProtectedRoute><Dashboard /></ProtectedRoute>\n          } />\n          <Route path="*" element={<h2>404 Not Found</h2>} />\n        </Routes>\n      </Suspense>\n    </BrowserRouter>\n  );\n}',
     lang:'javascript',
     keyPoints:['useParams() lấy URL params (:id)','useNavigate() programmatic navigation','lazy() + Suspense cho code splitting, giảm bundle size'],
     exercise:'Xây SPA portfolio với multi-page routing và transitions.'}
  ]},

  {id:'mid',name:'Mid-Level',badge:'mid',desc:'Custom Hooks, Context & Performance',lessons:[
    {id:'custom-hooks',title:'Custom Hooks',
     theory:'<p>Custom hooks extract logic tái sử dụng. Convention: <code>use*</code> prefix. Hooks composition: combine built-in hooks thành behavior phức tạp. Share logic giữa components mà không cần HOC hay render props.</p>',
     code:'import { useState, useEffect, useCallback } from "react";\n\n// useFetch - reusable data fetching hook\nfunction useFetch(url) {\n  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(null);\n\n  const refetch = useCallback(() => {\n    setLoading(true);\n    setError(null);\n    fetch(url)\n      .then(r => { if (!r.ok) throw new Error(r.statusText); return r.json(); })\n      .then(setData)\n      .catch(setError)\n      .finally(() => setLoading(false));\n  }, [url]);\n\n  useEffect(() => { refetch(); }, [refetch]);\n  return { data, loading, error, refetch };\n}\n\n// useLocalStorage - persist state\nfunction useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    const stored = localStorage.getItem(key);\n    return stored ? JSON.parse(stored) : initialValue;\n  });\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n  return [value, setValue];\n}\n\n// Usage\nfunction UserList() {\n  const { data: users, loading, error, refetch } = useFetch("/api/users");\n  const [theme, setTheme] = useLocalStorage("theme", "dark");\n  if (loading) return <p>Loading...</p>;\n  if (error) return <button onClick={refetch}>Retry</button>;\n  return <ul>{users.map(u => <li key={u.id}>{u.name}</li>)}</ul>;\n}',
     lang:'javascript',
     keyPoints:['Custom hook = function bắt đầu bằng use*','Extract + reuse logic giữa components','Hooks composition: kết hợp useState, useEffect, useCallback'],
     exercise:'Viết useDebounce, useMediaQuery, useIntersectionObserver hooks.'},

    {id:'context',title:'Context API & State Management',
     theory:'<p><code>Context</code> giải quyết prop drilling. <code>useReducer</code> cho complex state logic. Combine Context + useReducer = mini Redux. Zustand/Jotai cho global state nhẹ hơn.</p>',
     code:'import { createContext, useContext, useReducer } from "react";\n\n// Actions\nconst ACTIONS = { ADD: "ADD", TOGGLE: "TOGGLE", DELETE: "DELETE" };\n\nfunction todoReducer(state, action) {\n  switch (action.type) {\n    case ACTIONS.ADD:\n      return [...state, { id: Date.now(), title: action.title, done: false }];\n    case ACTIONS.TOGGLE:\n      return state.map(t => t.id === action.id ? {...t, done: !t.done} : t);\n    case ACTIONS.DELETE:\n      return state.filter(t => t.id !== action.id);\n    default: return state;\n  }\n}\n\nconst TodoContext = createContext();\n\nfunction TodoProvider({ children }) {\n  const [todos, dispatch] = useReducer(todoReducer, []);\n  return (\n    <TodoContext.Provider value={{ todos, dispatch }}>\n      {children}\n    </TodoContext.Provider>\n  );\n}\n\nfunction useTodos() {\n  const context = useContext(TodoContext);\n  if (!context) throw new Error("useTodos must be inside TodoProvider");\n  return context;\n}\n\n// Any nested component:\nfunction AddTodo() {\n  const { dispatch } = useTodos();\n  const [title, setTitle] = useState("");\n  return (\n    <form onSubmit={e => {\n      e.preventDefault();\n      dispatch({ type: ACTIONS.ADD, title });\n      setTitle("");\n    }}>\n      <input value={title} onChange={e => setTitle(e.target.value)} />\n    </form>\n  );\n}',
     lang:'javascript',
     keyPoints:['Context tránh prop drilling qua nhiều levels','useReducer cho state logic phức tạp (action → new state)','Custom hook (useTodos) wrap useContext cho DX tốt hơn'],
     exercise:'Xây dựng shopping cart với Context + useReducer.'},

    {id:'performance',title:'Performance Optimization',
     theory:'<p><code>React.memo</code> tránh re-render không cần thiết. <code>useMemo</code> cache giá trị tính toán. <code>useCallback</code> cache function references. React DevTools Profiler tìm bottleneck.</p>',
     code:'import { useState, useMemo, useCallback, memo } from "react";\n\n// memo: skip re-render nếu props không đổi\nconst ExpensiveList = memo(function({ items, onSelect }) {\n  console.log("ExpensiveList rendered");\n  return (\n    <ul>\n      {items.map(item => (\n        <li key={item.id} onClick={() => onSelect(item.id)}>\n          {item.name}\n        </li>\n      ))}\n    </ul>\n  );\n});\n\nfunction Dashboard() {\n  const [filter, setFilter] = useState("");\n  const [selectedId, setSelectedId] = useState(null);\n  const [items] = useState(() =>\n    Array.from({ length: 10000 }, (_, i) => ({\n      id: i, name: `Item ${i}`, category: i % 3 === 0 ? "A" : "B"\n    }))\n  );\n\n  // useMemo: cache expensive computation\n  const filtered = useMemo(() => {\n    return items.filter(i =>\n      i.name.toLowerCase().includes(filter.toLowerCase())\n    );\n  }, [items, filter]);\n\n  // useCallback: stable function reference\n  const handleSelect = useCallback((id) => {\n    setSelectedId(id);\n  }, []);\n\n  return (\n    <div>\n      <input value={filter} onChange={e => setFilter(e.target.value)} />\n      <p>Showing {filtered.length} items</p>\n      <ExpensiveList items={filtered} onSelect={handleSelect} />\n    </div>\n  );\n}',
     lang:'javascript',
     keyPoints:['React.memo: skip render nếu same props','useMemo: cache computed value, tránh tính lại mỗi render','useCallback: stable fn reference, cần cho memo children'],
     exercise:'Profile app với React DevTools, giảm re-renders 50%.'}
  ]},

  {id:'senior',name:'Senior',badge:'senior',desc:'Patterns & Server Components',lessons:[
    {id:'patterns',title:'Advanced Patterns & Architecture',
     theory:'<p>Compound Components cho flexible API. Render Props cho logic sharing. HOC pattern. Error Boundaries catch errors. React Query cho server state management.</p>',
     code:'import { Component } from "react";\n\n// Error Boundary (class component required)\nclass ErrorBoundary extends Component {\n  state = { hasError: false, error: null };\n  static getDerivedStateFromError(error) {\n    return { hasError: true, error };\n  }\n  componentDidCatch(error, info) {\n    console.error("Caught:", error, info);\n  }\n  render() {\n    if (this.state.hasError) {\n      return (\n        <div className="error-fallback">\n          <h2>Something went wrong</h2>\n          <pre>{this.state.error?.message}</pre>\n          <button onClick={() => this.setState({ hasError: false })}>\n            Try again\n          </button>\n        </div>\n      );\n    }\n    return this.props.children;\n  }\n}\n\n// React Query pattern\nimport { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";\n\nfunction useUsers() {\n  return useQuery({ queryKey: ["users"], queryFn: () =>\n    fetch("/api/users").then(r => r.json())\n  });\n}\n\nfunction useCreateUser() {\n  const qc = useQueryClient();\n  return useMutation({\n    mutationFn: (data) => fetch("/api/users", {\n      method: "POST", body: JSON.stringify(data),\n      headers: { "Content-Type": "application/json" }\n    }).then(r => r.json()),\n    onSuccess: () => qc.invalidateQueries({ queryKey: ["users"] })\n  });\n}',
     lang:'javascript',
     keyPoints:['Error Boundary: catch render errors, show fallback UI','React Query: cache, refetch, invalidate server state','Compound Components: flexible API với shared implicit state'],
     exercise:'Xây component library với Compound Components pattern.'},

    {id:'nextjs',title:'Next.js & Server Components',
     theory:'<p><strong>Next.js</strong> App Router: Server Components (RSC) mặc định, Client Components opt-in với <code>"use client"</code>. Server Actions cho form submissions. ISR, SSG, SSR cho rendering strategies.</p>',
     code:'// app/page.tsx - Server Component (default)\nasync function HomePage() {\n  // This runs on the server!\n  const posts = await fetch("https://api.example.com/posts",\n    { next: { revalidate: 3600 } } // ISR: revalidate every hour\n  ).then(r => r.json());\n\n  return (\n    <main>\n      <h1>Blog</h1>\n      {posts.map(post => (\n        <article key={post.id}>\n          <h2>{post.title}</h2>\n          <p>{post.excerpt}</p>\n        </article>\n      ))}\n      <LikeButton /> {/* Client Component */}\n    </main>\n  );\n}\n\n// components/LikeButton.tsx\n"use client";\nimport { useState } from "react";\n\nfunction LikeButton() {\n  const [likes, setLikes] = useState(0);\n  return (\n    <button onClick={() => setLikes(l => l + 1)}>\n      ❤️ {likes}\n    </button>\n  );\n}\n\n// app/actions.ts - Server Action\n"use server";\nexport async function createPost(formData) {\n  const title = formData.get("title");\n  await db.post.create({ data: { title } });\n  revalidatePath("/");\n}',
     lang:'javascript',
     keyPoints:['Server Components: fetch data trên server, zero JS client','use client directive cho interactive components','Server Actions: form submissions không cần API route'],
     exercise:'Xây blog với Next.js App Router: SSR, ISR, Server Actions.'}
  ]},

  {id:'master',name:'Master',badge:'master',desc:'Internals & React 19',lessons:[
    {id:'internals',title:'React Fiber & Reconciliation',
     theory:'<p>React Fiber là reconciliation engine. Virtual DOM diffing algorithm: O(n) heuristic. Concurrent rendering: time slicing, priority lanes. Understanding re-rendering rules.</p>',
     code:'// Understanding React rendering\nimport { useRef, useEffect, useState } from "react";\n\nfunction RenderTracker({ name, children }) {\n  const renderCount = useRef(0);\n  renderCount.current++;\n  \n  useEffect(() => {\n    console.log(`${name} rendered ${renderCount.current} times`);\n  });\n  \n  return (\n    <div style={{ border: "1px solid #333", padding: 8, margin: 4 }}>\n      <small>{name} (renders: {renderCount.current})</small>\n      {children}\n    </div>\n  );\n}\n\n// Key rules of React rendering:\n// 1. State change → component + all children re-render\n// 2. Props change check is referential (===)\n// 3. Context change → all consumers re-render\n// 4. React.memo prevents child re-render if same props\n\n// Concurrent features\nimport { useTransition, useDeferredValue } from "react";\n\nfunction SearchWithTransition() {\n  const [query, setQuery] = useState("");\n  const [isPending, startTransition] = useTransition();\n  const deferredQuery = useDeferredValue(query);\n\n  return (\n    <div>\n      <input value={query} onChange={e => {\n        // Urgent: update input immediately\n        setQuery(e.target.value);\n      }} />\n      {isPending && <span>Updating...</span>}\n      {/* Non-urgent: deferred rendering */}\n      <HeavyList filter={deferredQuery} />\n    </div>\n  );\n}',
     lang:'javascript',
     keyPoints:['Fiber: linked list tree, time-sliced rendering','useTransition: mark state update as non-urgent','useDeferredValue: defer expensive re-renders'],
     exercise:'Implement virtual scrolling list render 100k items smoothly.'},

    {id:'react19',title:'React 19 & Future',
     theory:'<p>React 19: <code>use()</code> hook cho promises/context, <code>useOptimistic</code> cho optimistic UI, <code>useFormStatus</code> cho form states. React Compiler auto-memoizes. Server Components matured.</p>',
     code:'// React 19 features\nimport { use, useOptimistic, Suspense } from "react";\n\n// use() - read promises & context directly\nfunction Comments({ commentsPromise }) {\n  const comments = use(commentsPromise); // suspends until resolved\n  return (\n    <ul>\n      {comments.map(c => <li key={c.id}>{c.text}</li>)}\n    </ul>\n  );\n}\n\nfunction Page() {\n  const commentsPromise = fetch("/api/comments").then(r => r.json());\n  return (\n    <Suspense fallback={<p>Loading comments...</p>}>\n      <Comments commentsPromise={commentsPromise} />\n    </Suspense>\n  );\n}\n\n// useOptimistic - instant UI update\nfunction TodoList({ todos, addTodo }) {\n  const [optimisticTodos, addOptimistic] = useOptimistic(\n    todos,\n    (state, newTodo) => [...state, { ...newTodo, pending: true }]\n  );\n\n  async function handleAdd(formData) {\n    const title = formData.get("title");\n    addOptimistic({ id: Date.now(), title, done: false });\n    await addTodo(title); // actual server call\n  }\n\n  return (\n    <form action={handleAdd}>\n      <input name="title" />\n      <ul>\n        {optimisticTodos.map(t => (\n          <li key={t.id} style={{ opacity: t.pending ? 0.5 : 1 }}>\n            {t.title}\n          </li>\n        ))}\n      </ul>\n    </form>\n  );\n}',
     lang:'javascript',
     keyPoints:['use() hook: read promises inside components with Suspense','useOptimistic: instant UI feedback trước server response','React Compiler: auto memo, không cần useMemo/useCallback thủ công'],
     exercise:'Build realtime dashboard với React 19, Suspense boundaries, optimistic updates.'}
  ]}
]
};
