const DATA_GO={id:'go',name:'Go',icon:'🐹',color:'#00ADD8',gradient:'linear-gradient(135deg,#00ADD8,#007D9C)',category:'language',description:'Cloud-native, microservices, concurrent programming, DevOps tools',
levels:[
{id:'newbie',name:'Newbie',badge:'newbie',desc:'Go cơ bản',lessons:[
{id:'intro',title:'Go Syntax & Types',theory:'<p><strong>Go</strong> (Golang) bởi Google. Compiled, statically typed, garbage collected. Nổi tiếng cho simplicity, concurrency, fast compilation. Dùng cho cloud/DevOps tools (Docker, K8s, Terraform).</p>',
code:'package main\n\nimport "fmt"\n\nfunc main() {\n\t// Variables\n\tvar name string = "DevMaster"\n\tage := 20 // short declaration\n\tactive := true\n\n\tfmt.Printf("Name: %s, Age: %d\\n", name, age)\n\n\t// Arrays & Slices\n\tnums := []int{1, 2, 3, 4, 5}\n\tnums = append(nums, 6)\n\tfmt.Println("Slice:", nums[:3]) // [1 2 3]\n\n\t// Maps\n\tscores := map[string]int{\n\t\t"math": 95,\n\t\t"cs":   88,\n\t}\n\tscores["english"] = 92\n\n\t// Struct\n\ttype User struct {\n\t\tName  string\n\t\tEmail string\n\t\tAge   int\n\t}\n\tuser := User{Name: "An", Email: "an@mail.com", Age: 20}\n\n\t// If with init statement\n\tif val, ok := scores["math"]; ok {\n\t\tfmt.Println("Math:", val)\n\t}\n\n\t// For (only loop in Go)\n\tfor i, v := range nums {\n\t\tfmt.Printf("Index %d: %d\\n", i, v)\n\t}\n}',lang:'go',keyPoints:[':= short variable declaration (type inferred)','Slices: dynamic arrays, append() để thêm','Maps: map[keyType]valueType, check existence với val, ok'],exercise:'Tạo chương trình quản lý contacts: add, search, delete.'},
{id:'functions',title:'Functions, Error Handling & Interfaces',theory:'<p>Go trả multiple values. Error handling explicit: <code>if err != nil</code>. Interfaces implicit (duck typing). Pointers cho pass-by-reference.</p>',
code:'package main\n\nimport (\n\t"errors"\n\t"fmt"\n\t"math"\n)\n\n// Multiple return values + error\nfunc divide(a, b float64) (float64, error) {\n\tif b == 0 {\n\t\treturn 0, errors.New("division by zero")\n\t}\n\treturn a / b, nil\n}\n\n// Interface (implicit implementation)\ntype Shape interface {\n\tArea() float64\n\tPerimeter() float64\n}\n\ntype Circle struct{ Radius float64 }\nfunc (c Circle) Area() float64      { return math.Pi * c.Radius * c.Radius }\nfunc (c Circle) Perimeter() float64  { return 2 * math.Pi * c.Radius }\n\ntype Rectangle struct{ W, H float64 }\nfunc (r Rectangle) Area() float64     { return r.W * r.H }\nfunc (r Rectangle) Perimeter() float64 { return 2 * (r.W + r.H) }\n\nfunc printShape(s Shape) {\n\tfmt.Printf("Area: %.2f, Perimeter: %.2f\\n", s.Area(), s.Perimeter())\n}\n\nfunc main() {\n\tresult, err := divide(10, 3)\n\tif err != nil {\n\t\tfmt.Println("Error:", err)\n\t\treturn\n\t}\n\tfmt.Printf("Result: %.2f\\n", result)\n\n\tprintShape(Circle{Radius: 5})\n\tprintShape(Rectangle{W: 3, H: 4})\n}',lang:'go',keyPoints:['Multiple returns: (value, error) pattern chuẩn Go','Interfaces implicit: struct tự implement nếu có đủ methods','Pointer receiver: func (s *Struct) Method() modify original'],exercise:'Xây calculator CLI với error handling, interface cho operations.'},
{id:'packages',title:'Packages, Modules & Testing',theory:'<p>Go modules quản lý dependencies. Package = directory. Exported names viết hoa chữ đầu. Testing built-in với <code>testing</code> package.</p>',
code:'// go.mod\n// module github.com/user/myapp\n// go 1.22\n\n// math/calc.go\npackage math\n\nfunc Add(a, b int) int { return a + b }\nfunc Multiply(a, b int) int { return a * b }\n\n// math/calc_test.go\npackage math\n\nimport "testing"\n\nfunc TestAdd(t *testing.T) {\n\ttests := []struct {\n\t\ta, b, want int\n\t}{\n\t\t{2, 3, 5},\n\t\t{-1, 1, 0},\n\t\t{0, 0, 0},\n\t}\n\tfor _, tt := range tests {\n\t\tgot := Add(tt.a, tt.b)\n\t\tif got != tt.want {\n\t\t\tt.Errorf("Add(%d, %d) = %d, want %d", tt.a, tt.b, got, tt.want)\n\t\t}\n\t}\n}\n\nfunc BenchmarkAdd(b *testing.B) {\n\tfor i := 0; i < b.N; i++ {\n\t\tAdd(100, 200)\n\t}\n}\n\n// Run: go test ./... -v\n// Benchmark: go test -bench=.',lang:'go',keyPoints:['Exported = viết Hoa chữ đầu, lowercase = private','Table-driven tests: slice of test cases + range loop','go test built-in, go test -bench cho benchmarks'],exercise:'Tạo package string utils với unit tests và benchmarks.'}
]},
{id:'junior',name:'Junior',badge:'junior',desc:'Concurrency & Web',lessons:[
{id:'goroutines',title:'Goroutines & Channels',theory:'<p><strong>Goroutines</strong> lightweight threads (2KB stack). <strong>Channels</strong> communication between goroutines. <code>select</code> multiplex channels. Go motto: "Don\'t communicate by sharing memory, share memory by communicating."</p>',
code:'package main\n\nimport (\n\t"fmt"\n\t"sync"\n\t"time"\n)\n\n// Goroutine + Channel\nfunc fetchURL(url string, ch chan<- string) {\n\ttime.Sleep(100 * time.Millisecond) // simulate\n\tch <- fmt.Sprintf("Fetched: %s", url)\n}\n\n// Worker pool pattern\nfunc worker(id int, jobs <-chan int, results chan<- int, wg *sync.WaitGroup) {\n\tdefer wg.Done()\n\tfor job := range jobs {\n\t\tfmt.Printf("Worker %d processing job %d\\n", id, job)\n\t\tresults <- job * 2\n\t}\n}\n\nfunc main() {\n\t// Fan-out: multiple goroutines\n\turls := []string{"google.com", "github.com", "go.dev"}\n\tch := make(chan string, len(urls))\n\tfor _, url := range urls {\n\t\tgo fetchURL(url, ch)\n\t}\n\tfor range urls {\n\t\tfmt.Println(<-ch)\n\t}\n\n\t// Worker pool\n\tjobs := make(chan int, 10)\n\tresults := make(chan int, 10)\n\tvar wg sync.WaitGroup\n\tfor w := 1; w <= 3; w++ {\n\t\twg.Add(1)\n\t\tgo worker(w, jobs, results, &wg)\n\t}\n\tfor j := 1; j <= 5; j++ {\n\t\tjobs <- j\n\t}\n\tclose(jobs)\n\twg.Wait()\n\tclose(results)\n}',lang:'go',keyPoints:['go func() starts goroutine (lightweight, 2KB stack)','Channels: make(chan T), send (<-), receive (->)','sync.WaitGroup: wait for multiple goroutines to finish'],exercise:'Xây concurrent web scraper: 10 workers, rate limiting.'},
{id:'web',title:'HTTP Server & REST API',theory:'<p>Go <code>net/http</code> stdlib mạnh. Frameworks: <strong>Gin, Echo, Chi</strong> cho routing. <code>encoding/json</code> cho serialization. Context cho request lifecycle.</p>',
code:'package main\n\nimport (\n\t"encoding/json"\n\t"log"\n\t"net/http"\n\t"strconv"\n)\n\ntype Todo struct {\n\tID    int    `json:"id"`\n\tTitle string `json:"title"`\n\tDone  bool   `json:"done"`\n}\n\nvar todos = []Todo{\n\t{ID: 1, Title: "Learn Go", Done: false},\n}\n\nfunc getTodos(w http.ResponseWriter, r *http.Request) {\n\tw.Header().Set("Content-Type", "application/json")\n\tjson.NewEncoder(w).Encode(todos)\n}\n\nfunc createTodo(w http.ResponseWriter, r *http.Request) {\n\tvar todo Todo\n\tif err := json.NewDecoder(r.Body).Decode(&todo); err != nil {\n\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n\t\treturn\n\t}\n\ttodo.ID = len(todos) + 1\n\ttodos = append(todos, todo)\n\tw.WriteHeader(http.StatusCreated)\n\tjson.NewEncoder(w).Encode(todo)\n}\n\nfunc main() {\n\tmux := http.NewServeMux()\n\tmux.HandleFunc("GET /api/todos", getTodos)\n\tmux.HandleFunc("POST /api/todos", createTodo)\n\n\tlog.Println("Server on :8080")\n\tlog.Fatal(http.ListenAndServe(":8080", mux))\n}',lang:'go',keyPoints:['net/http stdlib đủ mạnh cho production servers','json struct tags: `json:"field_name"` cho serialization','Go 1.22: method routing "GET /path" trong ServeMux'],exercise:'Xây REST API CRUD với middleware logging, auth.'},
{id:'context',title:'Context, Middleware & Error Patterns',theory:'<p><code>context.Context</code> truyền deadlines, cancellation, values qua call chain. Middleware pattern cho HTTP. Custom error types.</p>',
code:'package main\n\nimport (\n\t"context"\n\t"fmt"\n\t"log"\n\t"net/http"\n\t"time"\n)\n\n// Custom error type\ntype AppError struct {\n\tCode    int\n\tMessage string\n\tErr     error\n}\nfunc (e *AppError) Error() string { return fmt.Sprintf("%d: %s", e.Code, e.Message) }\nfunc (e *AppError) Unwrap() error { return e.Err }\n\n// Middleware\nfunc loggingMiddleware(next http.Handler) http.Handler {\n\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n\t\tstart := time.Now()\n\t\tlog.Printf("%s %s started", r.Method, r.URL.Path)\n\t\tnext.ServeHTTP(w, r)\n\t\tlog.Printf("%s %s took %v", r.Method, r.URL.Path, time.Since(start))\n\t})\n}\n\n// Context with timeout\nfunc fetchData(ctx context.Context, url string) ([]byte, error) {\n\tctx, cancel := context.WithTimeout(ctx, 5*time.Second)\n\tdefer cancel()\n\n\treq, _ := http.NewRequestWithContext(ctx, "GET", url, nil)\n\tresp, err := http.DefaultClient.Do(req)\n\tif err != nil {\n\t\treturn nil, &AppError{Code: 500, Message: "fetch failed", Err: err}\n\t}\n\tdefer resp.Body.Close()\n\treturn nil, nil // simplified\n}',lang:'go',keyPoints:['context.WithTimeout/WithCancel cho deadline management','Middleware: func(next http.Handler) http.Handler pattern','Custom errors implement error interface + Unwrap()'],exercise:'Xây HTTP server với timeout context, recovery middleware.'}
]},
{id:'mid',name:'Mid-Level',badge:'mid',desc:'Database, Generics & Production',lessons:[
{id:'database',title:'Database & ORM',theory:'<p>Go database: <code>database/sql</code> stdlib + drivers. <strong>GORM</strong> ORM hoặc <strong>sqlx</strong> cho query building. Connection pooling built-in. Migrations.</p>',
code:'package main\n\nimport (\n\t"database/sql"\n\t_ "github.com/lib/pq"\n\t"log"\n)\n\ntype User struct {\n\tID    int    `db:"id"`\n\tName  string `db:"name"`\n\tEmail string `db:"email"`\n}\n\nfunc main() {\n\tdb, err := sql.Open("postgres", "postgres://user:pass@localhost/mydb?sslmode=disable")\n\tif err != nil { log.Fatal(err) }\n\tdefer db.Close()\n\n\t// Connection pool\n\tdb.SetMaxOpenConns(25)\n\tdb.SetMaxIdleConns(5)\n\n\t// Query\n\trows, err := db.Query("SELECT id, name, email FROM users WHERE name LIKE $1", "%An%")\n\tif err != nil { log.Fatal(err) }\n\tdefer rows.Close()\n\n\tvar users []User\n\tfor rows.Next() {\n\t\tvar u User\n\t\tif err := rows.Scan(&u.ID, &u.Name, &u.Email); err != nil {\n\t\t\tlog.Fatal(err)\n\t\t}\n\t\tusers = append(users, u)\n\t}\n\n\t// Insert with returning\n\tvar id int\n\terr = db.QueryRow(\n\t\t"INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id",\n\t\t"Binh", "binh@mail.com",\n\t).Scan(&id)\n}',lang:'go',keyPoints:['database/sql: stdlib interface, driver-agnostic','Connection pooling: SetMaxOpenConns, SetMaxIdleConns','$1, $2 parameterized queries prevent SQL injection'],exercise:'Xây CRUD API với PostgreSQL + proper connection pooling.'},
{id:'generics',title:'Go Generics (1.18+)',theory:'<p>Go 1.18 thêm <strong>Generics</strong>. Type parameters với constraints. Comparable, any, constraints package. Generic data structures.</p>',
code:'package main\n\nimport "fmt"\n\n// Generic function\nfunc Filter[T any](items []T, predicate func(T) bool) []T {\n\tvar result []T\n\tfor _, item := range items {\n\t\tif predicate(item) {\n\t\t\tresult = append(result, item)\n\t\t}\n\t}\n\treturn result\n}\n\nfunc Map[T any, U any](items []T, transform func(T) U) []U {\n\tresult := make([]U, len(items))\n\tfor i, item := range items {\n\t\tresult[i] = transform(item)\n\t}\n\treturn result\n}\n\n// Generic struct\ntype Stack[T any] struct {\n\titems []T\n}\nfunc (s *Stack[T]) Push(item T)  { s.items = append(s.items, item) }\nfunc (s *Stack[T]) Pop() (T, bool) {\n\tif len(s.items) == 0 {\n\t\tvar zero T\n\t\treturn zero, false\n\t}\n\ttop := s.items[len(s.items)-1]\n\ts.items = s.items[:len(s.items)-1]\n\treturn top, true\n}\n\nfunc main() {\n\tnums := []int{1, 2, 3, 4, 5}\n\tevens := Filter(nums, func(n int) bool { return n%2 == 0 })\n\tdoubled := Map(nums, func(n int) int { return n * 2 })\n\tfmt.Println(evens, doubled)\n}',lang:'go',keyPoints:['[T any] type parameter với any constraint','[T comparable] cho types hỗ trợ == operator','Generic structs and methods cho reusable data structures'],exercise:'Implement generic LinkedList, Queue, HashMap.'},
{id:'production',title:'Production Go: Logging, Config, Graceful Shutdown',theory:'<p>Production patterns: structured logging (slog), config management, graceful shutdown, health checks. <code>os/signal</code> cho signal handling.</p>',
code:'package main\n\nimport (\n\t"context"\n\t"log/slog"\n\t"net/http"\n\t"os"\n\t"os/signal"\n\t"syscall"\n\t"time"\n)\n\nfunc main() {\n\t// Structured logging (Go 1.21)\n\tlogger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{\n\t\tLevel: slog.LevelInfo,\n\t}))\n\tslog.SetDefault(logger)\n\n\tmux := http.NewServeMux()\n\tmux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {\n\t\tw.WriteHeader(200)\n\t\tw.Write([]byte(`{"status":"ok"}`))\n\t})\n\n\tserver := &http.Server{\n\t\tAddr:         ":8080",\n\t\tHandler:      mux,\n\t\tReadTimeout:  10 * time.Second,\n\t\tWriteTimeout: 30 * time.Second,\n\t\tIdleTimeout:  60 * time.Second,\n\t}\n\n\t// Graceful shutdown\n\tgo func() {\n\t\tslog.Info("Server starting", "addr", ":8080")\n\t\tif err := server.ListenAndServe(); err != http.ErrServerClosed {\n\t\t\tslog.Error("Server error", "err", err)\n\t\t}\n\t}()\n\n\tquit := make(chan os.Signal, 1)\n\tsignal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)\n\t<-quit\n\n\tctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)\n\tdefer cancel()\n\tslog.Info("Shutting down gracefully...")\n\tserver.Shutdown(ctx)\n}',lang:'go',keyPoints:['slog: structured JSON logging (Go 1.21 stdlib)','Graceful shutdown: finish in-flight requests trước khi exit','Server timeouts: Read, Write, Idle cho security'],exercise:'Xây production-ready API server với all best practices.'}
]},
{id:'senior',name:'Senior',badge:'senior',desc:'Advanced Concurrency & Architecture',lessons:[
{id:'concurrency',title:'Advanced Concurrency Patterns',theory:'<p>Go concurrency patterns: Fan-out/Fan-in, Pipeline, Rate Limiter, Circuit Breaker. <code>sync.Mutex</code>, <code>sync.RWMutex</code>, <code>sync.Once</code>, <code>sync.Pool</code>.</p>',
code:'package main\n\nimport (\n\t"context"\n\t"sync"\n\t"time"\n)\n\n// Pipeline pattern\nfunc generator(nums ...int) <-chan int {\n\tout := make(chan int)\n\tgo func() {\n\t\tdefer close(out)\n\t\tfor _, n := range nums { out <- n }\n\t}()\n\treturn out\n}\n\nfunc square(in <-chan int) <-chan int {\n\tout := make(chan int)\n\tgo func() {\n\t\tdefer close(out)\n\t\tfor n := range in { out <- n * n }\n\t}()\n\treturn out\n}\n\n// Rate limiter\ntype RateLimiter struct {\n\ttokens chan struct{}\n}\n\nfunc NewRateLimiter(rate int, interval time.Duration) *RateLimiter {\n\trl := &RateLimiter{tokens: make(chan struct{}, rate)}\n\tgo func() {\n\t\tticker := time.NewTicker(interval / time.Duration(rate))\n\t\tfor range ticker.C {\n\t\t\tselect {\n\t\t\tcase rl.tokens <- struct{}{}:\n\t\t\tdefault:\n\t\t\t}\n\t\t}\n\t}()\n\treturn rl\n}\n\nfunc (rl *RateLimiter) Wait(ctx context.Context) error {\n\tselect {\n\tcase <-rl.tokens: return nil\n\tcase <-ctx.Done(): return ctx.Err()\n\t}\n}',lang:'go',keyPoints:['Pipeline: chain of stages connected by channels','Fan-out: multiple goroutines read from same channel','Rate limiter: token bucket algorithm with channels'],exercise:'Implement fan-out/fan-in pipeline cho image processing.'},
{id:'microservices',title:'Go Microservices Architecture',theory:'<p>Go ideal cho microservices: nhỏ, compile nhanh, low memory. gRPC cho service-to-service. Protobuf serialization. Distributed tracing với OpenTelemetry.</p>',
code:'// Proto definition\n// syntax = "proto3";\n// service UserService {\n//   rpc GetUser(GetUserRequest) returns (UserResponse);\n//   rpc ListUsers(ListUsersRequest) returns (stream UserResponse);\n// }\n\n// gRPC server implementation\ntype userServer struct {\n\tpb.UnimplementedUserServiceServer\n\tusers map[int64]*pb.UserResponse\n}\n\nfunc (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.UserResponse, error) {\n\tuser, ok := s.users[req.Id]\n\tif !ok {\n\t\treturn nil, status.Errorf(codes.NotFound, "user %d not found", req.Id)\n\t}\n\treturn user, nil\n}\n\n// Health check endpoint\nfunc healthHandler(w http.ResponseWriter, r *http.Request) {\n\tstatus := map[string]string{\n\t\t"status": "healthy",\n\t\t"version": os.Getenv("APP_VERSION"),\n\t\t"uptime": time.Since(startTime).String(),\n\t}\n\tjson.NewEncoder(w).Encode(status)\n}\n\n// Dockerfile for Go microservice\n// FROM golang:1.22-alpine AS builder\n// WORKDIR /app\n// COPY go.* ./\n// RUN go mod download\n// COPY . .\n// RUN CGO_ENABLED=0 go build -o server .\n// FROM scratch\n// COPY --from=builder /app/server /server\n// CMD ["/server"]',lang:'go',keyPoints:['gRPC + Protobuf: type-safe, fast service communication','FROM scratch: minimal Docker image (~10MB)','OpenTelemetry: distributed tracing across services'],exercise:'Xây 2 microservices gRPC communicate với nhau.'}
]},
{id:'master',name:'Master',badge:'master',desc:'Go Runtime & System Programming',lessons:[
{id:'runtime',title:'Go Runtime & Scheduler Internals',theory:'<p>Go runtime: GMP model (Goroutine, Machine/OS thread, Processor). Garbage collector: tri-color mark-and-sweep. Memory allocator: tcmalloc-inspired. Escape analysis.</p>',
code:'package main\n\nimport (\n\t"fmt"\n\t"runtime"\n\t"runtime/debug"\n\t"unsafe"\n)\n\nfunc main() {\n\t// Runtime info\n\tfmt.Println("GOMAXPROCS:", runtime.GOMAXPROCS(0))\n\tfmt.Println("NumGoroutine:", runtime.NumGoroutine())\n\tfmt.Println("NumCPU:", runtime.NumCPU())\n\n\t// GC tuning\n\tdebug.SetGCPercent(100)   // default: trigger GC at 100% heap growth\n\tdebug.SetMemoryLimit(1 << 30) // 1GB memory limit\n\n\t// Memory stats\n\tvar m runtime.MemStats\n\truntime.ReadMemStats(&m)\n\tfmt.Printf("Alloc: %d MB\\n", m.Alloc/1024/1024)\n\tfmt.Printf("Sys: %d MB\\n", m.Sys/1024/1024)\n\tfmt.Printf("NumGC: %d\\n", m.NumGC)\n\n\t// Escape analysis: go build -gcflags="-m"\n\t// Variables that escape to heap are more expensive\n\t// Stack allocation is free (no GC)\n\n\t// unsafe package (rare, advanced)\n\tvar x int64 = 42\n\tptr := unsafe.Pointer(&x)\n\tfmt.Println("Size of int64:", unsafe.Sizeof(x))\n\tfmt.Println("Pointer:", ptr)\n\n\t// Build tags\n\t// //go:build linux && amd64\n\t// //go:generate stringer -type=Status\n}',lang:'go',keyPoints:['GMP model: M:N scheduling, goroutines multiplexed on OS threads','Escape analysis: compiler decides stack vs heap allocation','GOGC/SetGCPercent controls GC frequency vs memory usage'],exercise:'Profile Go app: pprof CPU/memory, optimize allocations.'}
]}
]};
