// Java Full Curriculum
const DATA_JAVA = {
id:'java', name:'Java', icon:'☕', color:'#ED8B00',
gradient:'linear-gradient(135deg,#ED8B00,#5382A1)',
category:'language',
description:'Enterprise apps, Android, backend services, microservices',
levels:[
  {id:'newbie',name:'Newbie',badge:'newbie',desc:'Cú pháp Java cơ bản',lessons:[
    {id:'intro',title:'Hello World & Setup',
     theory:'<p>Java là ngôn ngữ <strong>OOP thuần</strong> — mọi code phải nằm trong class. <code>public static void main(String[] args)</code> là entry point. Compiled sang bytecode chạy trên JVM (Write Once, Run Anywhere).</p>',
     code:'public class HelloWorld {\n    public static void main(String[] args) {\n        String name = "DevMaster";\n        int year = 2025;\n        \n        System.out.println("Hello, " + name + "!");\n        System.out.printf("Welcome to %s - %d%n", name, year);\n        \n        // var (Java 10+) local type inference\n        var message = "Java is awesome!";\n        System.out.println(message);\n    }\n}',
     lang:'java',
     keyPoints:['Mọi code phải trong class, file name = class name','main() là entry point duy nhất','var (Java 10+) suy luận kiểu tự động cho local variables'],
     exercise:'Viết chương trình nhập tên và tuổi, in ra năm sinh.'},

    {id:'types-control',title:'Kiểu dữ liệu & Điều khiển',
     theory:'<p>Java có 8 <strong>primitive types</strong>: byte, short, int, long, float, double, boolean, char. Wrapper classes (Integer, Double...) cho phép dùng như object. <code>String</code> là reference type, immutable.</p>',
     code:'public class TypesDemo {\n    public static void main(String[] args) {\n        // Primitives\n        int age = 20;\n        double gpa = 3.75;\n        boolean active = true;\n        char grade = \'A\';\n\n        // String\n        String name = "Minh";\n        System.out.println(name.length());       // 4\n        System.out.println(name.toUpperCase());  // MINH\n\n        // Switch Expression (Java 14+)\n        String result = switch (grade) {\n            case \'A\' -> "Excellent";\n            case \'B\' -> "Good";\n            case \'C\' -> "Average";\n            default -> "Try harder";\n        };\n        System.out.println(result);\n\n        // Enhanced for + ternary\n        int[] scores = {85, 92, 67, 78, 95};\n        for (int s : scores) {\n            String status = s >= 70 ? "Pass" : "Fail";\n            System.out.println(s + ": " + status);\n        }\n    }\n}',
     lang:'java',
     keyPoints:['8 primitives: int, double, boolean, char... + wrapper classes','String immutable, dùng StringBuilder cho nối chuỗi nhiều','Switch expression (Java 14+): case -> value thay case: break'],
     exercise:'Viết chương trình máy tính đơn giản (+, -, *, /) dùng switch.'},

    {id:'arrays-methods',title:'Mảng, Hàm & ArrayList',
     theory:'<p>Java array cố định kích thước. <code>ArrayList</code> là mảng động. Methods phải khai báo return type. <code>static</code> methods gọi không cần object.</p>',
     code:'import java.util.ArrayList;\nimport java.util.Collections;\n\npublic class ArraysDemo {\n    // Static method\n    static int[] findMinMax(int[] arr) {\n        int min = arr[0], max = arr[0];\n        for (int n : arr) {\n            if (n < min) min = n;\n            if (n > max) max = n;\n        }\n        return new int[]{min, max};\n    }\n\n    // Overloading\n    static double average(int[] nums) {\n        int sum = 0;\n        for (int n : nums) sum += n;\n        return (double) sum / nums.length;\n    }\n\n    public static void main(String[] args) {\n        // Array (fixed size)\n        int[] scores = {85, 92, 67, 78};\n        int[] mm = findMinMax(scores);\n        System.out.printf("Min: %d, Max: %d%n", mm[0], mm[1]);\n\n        // ArrayList (dynamic)\n        ArrayList<String> tasks = new ArrayList<>();\n        tasks.add("Code");\n        tasks.add("Test");\n        tasks.add("Deploy");\n        tasks.remove("Test");\n        Collections.sort(tasks);\n\n        for (int i = 0; i < tasks.size(); i++) {\n            System.out.println((i+1) + ". " + tasks.get(i));\n        }\n    }\n}',
     lang:'java',
     keyPoints:['Array cố định: int[] arr = new int[10]','ArrayList<T> mảng động, chỉ chứa Objects (không primitive)','Method overloading: cùng tên, khác parameters'],
     exercise:'Viết hàm loại bỏ phần tử trùng lặp trong ArrayList.'}
  ]},

  {id:'junior',name:'Junior',badge:'junior',desc:'OOP hoàn chỉnh & Collections',lessons:[
    {id:'oop',title:'OOP: Class, Inheritance, Interface',
     theory:'<p>Java OOP 4 trụ cột: <strong>Encapsulation</strong> (private + getters/setters), <strong>Inheritance</strong> (extends), <strong>Polymorphism</strong> (override), <strong>Abstraction</strong> (abstract class + interface).</p>',
     code:'interface Payable {\n    double calculatePay();\n}\n\nabstract class Employee implements Payable {\n    protected String name;\n    protected double baseSalary;\n\n    public Employee(String name, double salary) {\n        this.name = name;\n        this.baseSalary = salary;\n    }\n    abstract String getRole();\n    \n    @Override\n    public String toString() {\n        return name + " (" + getRole() + "): $" + calculatePay();\n    }\n}\n\nclass Developer extends Employee {\n    private int projectCount;\n    public Developer(String n, double s, int p) {\n        super(n, s);\n        this.projectCount = p;\n    }\n    String getRole() { return "Developer"; }\n    public double calculatePay() {\n        return baseSalary + projectCount * 500;\n    }\n}\n\nclass Manager extends Employee {\n    private int teamSize;\n    public Manager(String n, double s, int t) {\n        super(n, s);\n        this.teamSize = t;\n    }\n    String getRole() { return "Manager"; }\n    public double calculatePay() {\n        return baseSalary * (1 + teamSize * 0.05);\n    }\n}',
     lang:'java',
     keyPoints:['interface: contract thuần, abstract: class bán hoàn chỉnh','@Override annotation bắt lỗi sai method signature','Polymorphism: Employee e = new Developer() rồi gọi e.calculatePay()'],
     exercise:'Tạo hierarchy Shape interface → Circle, Rectangle, Triangle.'},

    {id:'collections-streams',title:'Collections Framework & Streams',
     theory:'<p>Java Collections: <code>List</code>, <code>Set</code>, <code>Map</code>, <code>Queue</code>. <strong>Streams API</strong> (Java 8+) cho functional-style operations: filter, map, reduce, collect.</p>',
     code:'import java.util.*;\nimport java.util.stream.*;\n\npublic class StreamsDemo {\n    record Student(String name, double gpa, String major) {}\n\n    public static void main(String[] args) {\n        var students = List.of(\n            new Student("An", 8.5, "CS"),\n            new Student("Binh", 9.2, "CS"),\n            new Student("Chi", 7.8, "Math"),\n            new Student("Dung", 6.5, "CS"),\n            new Student("Em", 9.0, "Math")\n        );\n\n        // Filter + map + collect\n        var topCS = students.stream()\n            .filter(s -> s.major().equals("CS"))\n            .filter(s -> s.gpa() >= 8.0)\n            .sorted(Comparator.comparingDouble(Student::gpa).reversed())\n            .map(Student::name)\n            .collect(Collectors.toList());\n        System.out.println("Top CS: " + topCS);\n\n        // Group by major\n        var byMajor = students.stream()\n            .collect(Collectors.groupingBy(Student::major));\n        byMajor.forEach((major, list) ->\n            System.out.println(major + ": " + list.size()));\n\n        // Statistics\n        var stats = students.stream()\n            .mapToDouble(Student::gpa)\n            .summaryStatistics();\n        System.out.printf("Avg: %.2f, Max: %.1f%n",\n            stats.getAverage(), stats.getMax());\n    }\n}',
     lang:'java',
     keyPoints:['Stream: filter → map → collect pipeline','Collectors: toList, groupingBy, joining, summarizing','record (Java 16+): immutable data class tự tạo equals/hashCode'],
     exercise:'Dùng Streams xử lý danh sách đơn hàng: tổng doanh thu theo tháng.'},

    {id:'exceptions-generics',title:'Exceptions & Generics',
     theory:'<p><strong>Checked exceptions</strong> bắt buộc try/catch hoặc throws. <strong>Unchecked</strong> (RuntimeException) không bắt buộc. Generics (<code><T></code>) tạo type-safe classes/methods.</p>',
     code:'// Custom exception\nclass InsufficientFundsException extends Exception {\n    private final double balance;\n    private final double amount;\n    public InsufficientFundsException(double bal, double amt) {\n        super("Need $" + amt + ", have $" + bal);\n        this.balance = bal;\n        this.amount = amt;\n    }\n}\n\n// Generic class\nclass Result<T> {\n    private final T value;\n    private final String error;\n    \n    private Result(T value, String error) {\n        this.value = value;\n        this.error = error;\n    }\n    \n    public static <T> Result<T> ok(T value) {\n        return new Result<>(value, null);\n    }\n    public static <T> Result<T> fail(String error) {\n        return new Result<>(null, error);\n    }\n    \n    public boolean isOk() { return error == null; }\n    public T getValue() { return value; }\n    public String getError() { return error; }\n}\n\n// Usage\npublic class Main {\n    static Result<Integer> divide(int a, int b) {\n        if (b == 0) return Result.fail("Division by zero");\n        return Result.ok(a / b);\n    }\n    public static void main(String[] args) {\n        var result = divide(10, 3);\n        if (result.isOk())\n            System.out.println("Result: " + result.getValue());\n    }\n}',
     lang:'java',
     keyPoints:['Checked: IOException, SQLException → phải handle','Unchecked: NullPointer, IndexOutOfBounds → runtime errors','Generics <T>: type-safe containers, tránh casting'],
     exercise:'Viết generic class Pair<A,B> và Stack<T> type-safe.'}
  ]},

  {id:'mid',name:'Mid-Level',badge:'mid',desc:'Design Patterns & Database',lessons:[
    {id:'design-patterns',title:'Design Patterns trong Java',
     theory:'<p>Java là ngôn ngữ lý tưởng cho Design Patterns. <strong>Builder</strong> cho object creation phức tạp. <strong>Observer</strong> cho event handling. <strong>Strategy</strong> cho algorithms thay đổi runtime.</p>',
     code:'import java.util.*;\n\n// Builder Pattern\nclass HttpRequest {\n    private final String url;\n    private final String method;\n    private final Map<String,String> headers;\n    private final String body;\n\n    private HttpRequest(Builder b) {\n        this.url = b.url;\n        this.method = b.method;\n        this.headers = b.headers;\n        this.body = b.body;\n    }\n\n    static class Builder {\n        private String url;\n        private String method = "GET";\n        private Map<String,String> headers = new HashMap<>();\n        private String body;\n\n        Builder(String url) { this.url = url; }\n        Builder method(String m) { method = m; return this; }\n        Builder header(String k, String v) {\n            headers.put(k, v); return this;\n        }\n        Builder body(String b) { body = b; return this; }\n        HttpRequest build() { return new HttpRequest(this); }\n    }\n\n    @Override\n    public String toString() {\n        return method + " " + url + " headers=" + headers;\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        var req = new HttpRequest.Builder("https://api.example.com")\n            .method("POST")\n            .header("Content-Type", "application/json")\n            .header("Authorization", "Bearer token")\n            .body("{\\\"name\\\": \\\"test\\\"}")\n            .build();\n        System.out.println(req);\n    }\n}',
     lang:'java',
     keyPoints:['Builder: fluent API cho object creation phức tạp','Observer: event system với listeners/subscribers','Factory: tạo objects mà không expose implementation'],
     exercise:'Implement Observer pattern cho notification system.'},

    {id:'concurrency',title:'Concurrency & Multithreading',
     theory:'<p>Java threading: <code>Thread</code>, <code>Runnable</code>, <code>ExecutorService</code>. <code>synchronized</code> bảo vệ shared data. <code>CompletableFuture</code> cho async chains. <code>Virtual Threads</code> (Java 21) cho lightweight concurrency.</p>',
     code:'import java.util.concurrent.*;\nimport java.util.stream.*;\n\npublic class ConcurrencyDemo {\n    public static void main(String[] args) throws Exception {\n        // ExecutorService\n        var executor = Executors.newFixedThreadPool(4);\n\n        // CompletableFuture chaining\n        CompletableFuture<String> future =\n            CompletableFuture.supplyAsync(() -> {\n                // Simulate API call\n                try { Thread.sleep(1000); }\n                catch (InterruptedException e) {}\n                return "Raw Data";\n            }, executor)\n            .thenApplyAsync(data -> {\n                return data.toUpperCase();\n            })\n            .thenApplyAsync(data -> {\n                return "Processed: " + data;\n            });\n\n        System.out.println(future.get()); // Processed: RAW DATA\n\n        // Parallel Streams\n        long sum = LongStream.rangeClosed(1, 10_000_000)\n            .parallel()\n            .sum();\n        System.out.println("Sum: " + sum);\n\n        executor.shutdown();\n    }\n}',
     lang:'java',
     keyPoints:['ExecutorService quản lý thread pool','CompletableFuture: async chaining với thenApply, thenCompose','Virtual Threads (Java 21): Thread.startVirtualThread() nhẹ hơn 1000x'],
     exercise:'Viết parallel file downloader với CompletableFuture.'},

    {id:'jpa-database',title:'JPA & Database Access',
     theory:'<p><strong>JPA</strong> (Java Persistence API) map objects ↔ database tables. <code>@Entity</code>, <code>@Id</code>, <code>@OneToMany</code> cho ORM. Spring Data JPA auto-generate queries từ method names.</p>',
     code:'import javax.persistence.*;\nimport java.util.List;\n\n@Entity\n@Table(name = "users")\nclass User {\n    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n\n    @Column(nullable = false, unique = true)\n    private String email;\n\n    private String name;\n\n    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL)\n    private List<Post> posts;\n\n    // Constructors, getters, setters\n    public User() {}\n    public User(String name, String email) {\n        this.name = name;\n        this.email = email;\n    }\n}\n\n@Entity\nclass Post {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    private String title;\n    private String content;\n\n    @ManyToOne\n    @JoinColumn(name = "user_id")\n    private User author;\n}\n\n// Spring Data JPA Repository\ninterface UserRepository extends JpaRepository<User, Long> {\n    List<User> findByNameContaining(String name);\n    Optional<User> findByEmail(String email);\n    @Query("SELECT u FROM User u WHERE u.posts.size > :min")\n    List<User> findActiveUsers(@Param("min") int min);\n}',
     lang:'java',
     keyPoints:['@Entity map class → table, @Id cho primary key','@OneToMany/@ManyToOne cho relationships','Spring Data JPA: query methods tự generate từ tên method'],
     exercise:'Tạo entity Order → OrderItem với JPA và viết custom queries.'}
  ]},

  {id:'senior',name:'Senior',badge:'senior',desc:'Spring Boot & Architecture',lessons:[
    {id:'spring-boot',title:'Spring Boot REST API',
     theory:'<p><strong>Spring Boot</strong> là framework enterprise Java phổ biến nhất. Auto-configuration, dependency injection, embedded server. <code>@RestController</code> cho REST API, <code>@Service</code> cho business logic.</p>',
     code:'@RestController\n@RequestMapping("/api/users")\npublic class UserController {\n    private final UserService userService;\n\n    public UserController(UserService userService) {\n        this.userService = userService;\n    }\n\n    @GetMapping\n    public ResponseEntity<List<UserDTO>> findAll(\n            @RequestParam(defaultValue = "0") int page,\n            @RequestParam(defaultValue = "10") int size) {\n        return ResponseEntity.ok(userService.findAll(page, size));\n    }\n\n    @PostMapping\n    public ResponseEntity<UserDTO> create(@Valid @RequestBody CreateUserDTO dto) {\n        var user = userService.create(dto);\n        return ResponseEntity.status(201).body(user);\n    }\n\n    @PutMapping("/{id}")\n    public ResponseEntity<UserDTO> update(\n            @PathVariable Long id,\n            @Valid @RequestBody UpdateUserDTO dto) {\n        return ResponseEntity.ok(userService.update(id, dto));\n    }\n\n    @DeleteMapping("/{id}")\n    public ResponseEntity<Void> delete(@PathVariable Long id) {\n        userService.delete(id);\n        return ResponseEntity.noContent().build();\n    }\n\n    @ExceptionHandler(NotFoundException.class)\n    public ResponseEntity<ErrorResponse> handleNotFound(NotFoundException e) {\n        return ResponseEntity.status(404)\n            .body(new ErrorResponse(e.getMessage()));\n    }\n}',
     lang:'java',
     keyPoints:['@RestController = @Controller + @ResponseBody','@Valid + DTO pattern tách request/response từ entity','Constructor injection (không @Autowired) cho testability'],
     exercise:'Xây dựng REST API e-commerce với Spring Boot + JPA.'},

    {id:'spring-security',title:'Security & Authentication',
     theory:'<p>Spring Security cho authentication (ai là ai) và authorization (quyền truy cập). JWT (JSON Web Token) cho stateless auth. <code>SecurityFilterChain</code> cấu hình security rules.</p>',
     code:'@Configuration\n@EnableWebSecurity\npublic class SecurityConfig {\n    @Bean\n    public SecurityFilterChain securityFilterChain(\n            HttpSecurity http) throws Exception {\n        return http\n            .csrf(csrf -> csrf.disable())\n            .sessionManagement(s -> s\n                .sessionCreationPolicy(SessionCreationPolicy.STATELESS))\n            .authorizeHttpRequests(auth -> auth\n                .requestMatchers("/api/auth/**").permitAll()\n                .requestMatchers("/api/admin/**").hasRole("ADMIN")\n                .anyRequest().authenticated())\n            .addFilterBefore(jwtFilter(), UsernamePasswordAuthenticationFilter.class)\n            .build();\n    }\n}\n\n// JWT Service\n@Service\npublic class JwtService {\n    private final String SECRET = "your-secret-key";\n\n    public String generateToken(User user) {\n        return Jwts.builder()\n            .setSubject(user.getEmail())\n            .claim("roles", user.getRoles())\n            .setIssuedAt(new Date())\n            .setExpiration(new Date(System.currentTimeMillis() + 86400000))\n            .signWith(SignatureAlgorithm.HS256, SECRET)\n            .compact();\n    }\n\n    public String extractEmail(String token) {\n        return Jwts.parser()\n            .setSigningKey(SECRET)\n            .parseClaimsJws(token)\n            .getBody()\n            .getSubject();\n    }\n}',
     lang:'java',
     keyPoints:['SecurityFilterChain cấu hình auth rules','JWT: stateless authentication, token-based','@PreAuthorize("hasRole(\'ADMIN\')") cho method-level security'],
     exercise:'Implement login/register API với JWT + refresh token.'},

    {id:'testing-architecture',title:'Testing & Clean Architecture',
     theory:'<p>Java testing pyramid: Unit (JUnit 5) → Integration (@SpringBootTest) → E2E. Clean Architecture: layers tách biệt (Controller → Service → Repository). <code>@MockBean</code> cho unit testing.</p>',
     code:'// Unit test with JUnit 5 + Mockito\n@ExtendWith(MockitoExtension.class)\nclass UserServiceTest {\n    @Mock\n    private UserRepository userRepo;\n    @InjectMocks\n    private UserService userService;\n\n    @Test\n    void shouldCreateUser() {\n        var dto = new CreateUserDTO("An", "an@mail.com");\n        var savedUser = new User(1L, "An", "an@mail.com");\n        when(userRepo.save(any(User.class))).thenReturn(savedUser);\n\n        var result = userService.create(dto);\n\n        assertEquals("An", result.name());\n        verify(userRepo, times(1)).save(any());\n    }\n\n    @Test\n    void shouldThrowWhenUserNotFound() {\n        when(userRepo.findById(99L)).thenReturn(Optional.empty());\n        assertThrows(NotFoundException.class,\n            () -> userService.findById(99L));\n    }\n}\n\n// Integration test\n@SpringBootTest\n@AutoConfigureMockMvc\nclass UserControllerIT {\n    @Autowired MockMvc mockMvc;\n\n    @Test\n    void shouldCreateUser() throws Exception {\n        mockMvc.perform(post("/api/users")\n            .contentType(MediaType.APPLICATION_JSON)\n            .content("{\\\"name\\\":\\\"An\\\",\\\"email\\\":\\\"an@mail.com\\\"}"))\n            .andExpect(status().isCreated())\n            .andExpect(jsonPath("$.name").value("An"));\n    }\n}',
     lang:'java',
     keyPoints:['JUnit 5: @Test, assertEquals, assertThrows','Mockito: @Mock, when().thenReturn(), verify()','@SpringBootTest cho integration test với full context'],
     exercise:'Viết unit + integration tests cho Order service đạt 80% coverage.'}
  ]},

  {id:'master',name:'Master',badge:'master',desc:'JVM Internals & Performance',lessons:[
    {id:'jvm-internals',title:'JVM Internals & Performance',
     theory:'<p>Hiểu JVM: Heap (Young/Old Gen), GC algorithms (G1, ZGC), JIT compilation. Profiling với JFR (Java Flight Recorder). Memory tuning cho production.</p>',
     code:'// Memory-efficient patterns\nimport java.lang.ref.WeakReference;\nimport java.util.concurrent.ConcurrentHashMap;\n\npublic class PerformanceDemo {\n    // Object pooling\n    private static final ConcurrentHashMap<String, WeakReference<byte[]>> cache\n        = new ConcurrentHashMap<>();\n\n    static byte[] getCached(String key, int size) {\n        var ref = cache.get(key);\n        byte[] data = (ref != null) ? ref.get() : null;\n        if (data == null) {\n            data = new byte[size]; // expensive allocation\n            cache.put(key, new WeakReference<>(data));\n        }\n        return data;\n    }\n\n    public static void main(String[] args) {\n        // JVM flags for production:\n        // -Xms4g -Xmx4g (fixed heap size)\n        // -XX:+UseZGC (low-latency GC)\n        // -XX:+FlightRecorder (profiling)\n\n        Runtime rt = Runtime.getRuntime();\n        long totalMB = rt.totalMemory() / 1024 / 1024;\n        long freeMB = rt.freeMemory() / 1024 / 1024;\n        System.out.printf("Memory: %dMB used / %dMB total%n",\n            totalMB - freeMB, totalMB);\n        System.out.println("Processors: " + rt.availableProcessors());\n    }\n}',
     lang:'java',
     keyPoints:['G1GC default Java 11+, ZGC cho <1ms pause','JFR (Flight Recorder) zero-overhead profiling','WeakReference cho cache, tự GC khi hết memory'],
     exercise:'Profile ứng dụng, tìm memory leak và tối ưu GC.'},

    {id:'modern-java',title:'Modern Java 17-21 Features',
     theory:'<p>Java phát triển nhanh: <code>Records</code> (16), <code>Sealed classes</code> (17), <code>Pattern matching</code> (17-21), <code>Virtual threads</code> (21). Nắm vững modern Java để viết code ngắn gọn, hiệu quả.</p>',
     code:'// Records (Java 16)\nrecord Point(double x, double y) {\n    double distanceTo(Point other) {\n        return Math.sqrt(Math.pow(x - other.x, 2)\n                       + Math.pow(y - other.y, 2));\n    }\n}\n\n// Sealed classes (Java 17)\nsealed interface Shape permits Circle, Rect, Triangle {}\nrecord Circle(double r) implements Shape {}\nrecord Rect(double w, double h) implements Shape {}\nrecord Triangle(double b, double h) implements Shape {}\n\n// Pattern matching (Java 21)\nstatic double area(Shape shape) {\n    return switch (shape) {\n        case Circle c -> Math.PI * c.r() * c.r();\n        case Rect r -> r.w() * r.h();\n        case Triangle t -> 0.5 * t.b() * t.h();\n    };\n}\n\npublic class ModernJava {\n    public static void main(String[] args) throws Exception {\n        // Virtual Threads (Java 21)\n        var threads = new java.util.ArrayList<Thread>();\n        for (int i = 0; i < 10000; i++) {\n            final int id = i;\n            threads.add(Thread.startVirtualThread(() -> {\n                // Each virtual thread is ultra-lightweight\n                try { Thread.sleep(100); }\n                catch (InterruptedException e) {}\n            }));\n        }\n        for (var t : threads) t.join();\n        System.out.println("10000 virtual threads done!");\n\n        // Pattern matching\n        Shape s = new Circle(5);\n        System.out.printf("Area: %.2f%n", area(s));\n    }\n}',
     lang:'java',
     keyPoints:['record = immutable data class (equals, hashCode, toString miễn phí)','sealed interface giới hạn implementations → exhaustive switch','Virtual threads: 10M threads cùng lúc, nhẹ hơn OS thread 1000x'],
     exercise:'Refactor legacy code sang modern Java: records, sealed, pattern matching.'}
  ]}
]
};
