// C# Full Curriculum
const DATA_CSHARP = {
id:'csharp', name:'C#', icon:'🟣', color:'#68217A',
gradient:'linear-gradient(135deg,#68217A,#512BD4)',
category:'language',
description:'.NET, game dev (Unity), enterprise, cross-platform apps',
levels:[
  {id:'newbie',name:'Newbie',badge:'newbie',desc:'C# cơ bản',lessons:[
    {id:'intro',title:'C# Syntax & Types',
     theory:'<p><strong>C#</strong> là ngôn ngữ OOP mạnh mẽ trên <code>.NET</code> platform. Type-safe, garbage-collected, cross-platform. Dùng cho web (ASP.NET), desktop (WPF/MAUI), game (Unity).</p>',
     code:'using System;\n\nclass Program\n{\n    static void Main(string[] args)\n    {\n        // Variables & types\n        string name = "DevMaster";\n        int age = 20;\n        double gpa = 8.5;\n        bool isActive = true;\n\n        // String interpolation\n        Console.WriteLine($"Hello {name}, age: {age}");\n\n        // var - type inference\n        var items = new List<string> { "C#", "Java", "Python" };\n\n        // Null safety\n        string? nullableName = null;\n        string displayName = nullableName ?? "Anonymous";\n\n        // Pattern matching\n        object obj = 42;\n        if (obj is int number)\n        {\n            Console.WriteLine($"Number: {number}");\n        }\n\n        // Switch expression\n        string grade = gpa switch\n        {\n            >= 9.0 => "A",\n            >= 8.0 => "B",\n            >= 7.0 => "C",\n            _ => "D"\n        };\n    }\n}',
     lang:'csharp',
     keyPoints:['C# type-safe: string, int, double, bool, List<T>','$ string interpolation, ?? null coalescing','Pattern matching: is, switch expression cho clean logic'],
     exercise:'Tạo console app tính điểm trung bình sinh viên.'},

    {id:'oop',title:'OOP: Classes, Interfaces, Records',
     theory:'<p>C# hỗ trợ OOP đầy đủ: <code>class</code>, <code>interface</code>, <code>abstract</code>, <code>sealed</code>. <code>record</code> (C# 9) cho immutable data. <code>properties</code> thay getters/setters.</p>',
     code:'// Interface\npublic interface IRepository<T> where T : class\n{\n    T? GetById(int id);\n    IEnumerable<T> GetAll();\n    void Add(T entity);\n    void Delete(int id);\n}\n\n// Record (immutable data)\npublic record Product(int Id, string Name, decimal Price)\n{\n    public decimal WithTax(decimal rate) => Price * (1 + rate);\n}\n\n// Class implementing interface\npublic class ProductRepository : IRepository<Product>\n{\n    private readonly List<Product> _products = new();\n\n    public Product? GetById(int id) => \n        _products.FirstOrDefault(p => p.Id == id);\n\n    public IEnumerable<Product> GetAll() => _products.AsReadOnly();\n\n    public void Add(Product entity) => _products.Add(entity);\n\n    public void Delete(int id) =>\n        _products.RemoveAll(p => p.Id == id);\n}\n\n// Usage\nvar repo = new ProductRepository();\nrepo.Add(new Product(1, "Laptop", 999.99m));\nvar product = repo.GetById(1);\nvar updated = product! with { Price = 899.99m }; // immutable update',
     lang:'csharp',
     keyPoints:['interface cho abstraction, class cho implementation','record cho immutable data types (value semantics)','with expression tạo copy với modified properties'],
     exercise:'Xây student management system với interfaces và records.'},

    {id:'collections',title:'Collections & LINQ',
     theory:'<p><strong>LINQ</strong> (Language Integrated Query) query data trực tiếp trong C#. Giống SQL nhưng cho objects, arrays, databases. <code>Where, Select, OrderBy, GroupBy</code>.</p>',
     code:'using System.Linq;\n\nvar students = new List<Student>\n{\n    new("An", 8.5, "CS"),\n    new("Binh", 9.2, "CS"),\n    new("Chi", 7.8, "Math"),\n    new("Duy", 6.5, "Math"),\n    new("Em", 9.0, "CS"),\n};\n\n// LINQ query syntax\nvar topCS = from s in students\n            where s.Major == "CS" && s.GPA >= 8.0\n            orderby s.GPA descending\n            select new { s.Name, s.GPA };\n\n// LINQ method syntax (preferred)\nvar result = students\n    .Where(s => s.Major == "CS")\n    .OrderByDescending(s => s.GPA)\n    .Select(s => $"{s.Name}: {s.GPA}")\n    .ToList();\n\n// GroupBy\nvar byMajor = students\n    .GroupBy(s => s.Major)\n    .Select(g => new\n    {\n        Major = g.Key,\n        Count = g.Count(),\n        AvgGPA = g.Average(s => s.GPA)\n    });\n\n// Aggregation\nvar stats = new\n{\n    Max = students.Max(s => s.GPA),\n    Min = students.Min(s => s.GPA),\n    Avg = students.Average(s => s.GPA),\n    Total = students.Count\n};\n\nrecord Student(string Name, double GPA, string Major);',
     lang:'csharp',
     keyPoints:['LINQ: Where (filter), Select (transform), OrderBy (sort)','Method syntax: .Where().Select() chain cho readability','GroupBy cho statistics theo nhóm, Aggregate cho tổng hợp'],
     exercise:'Dùng LINQ phân tích dataset: top N, group stats, filtering.'}
  ]},

  {id:'junior',name:'Junior',badge:'junior',desc:'Async, Generics & ASP.NET',lessons:[
    {id:'async',title:'Async Programming',
     theory:'<p>C# <code>async/await</code> cho non-blocking I/O. <code>Task<T></code> represent async operation. <code>Task.WhenAll</code> chạy concurrent. <code>CancellationToken</code> cho cancellation.</p>',
     code:'using System.Net.Http;\n\npublic class UserService\n{\n    private readonly HttpClient _http;\n\n    public UserService(HttpClient http) => _http = http;\n\n    public async Task<User?> GetUserAsync(int id, CancellationToken ct = default)\n    {\n        var response = await _http.GetAsync($"/api/users/{id}", ct);\n        response.EnsureSuccessStatusCode();\n        return await response.Content.ReadFromJsonAsync<User>(ct);\n    }\n\n    public async Task<List<User>> GetManyUsersAsync(int[] ids)\n    {\n        var tasks = ids.Select(id => GetUserAsync(id));\n        var results = await Task.WhenAll(tasks);\n        return results.Where(u => u != null).ToList()!;\n    }\n\n    // With timeout\n    public async Task<User?> GetWithTimeout(int id)\n    {\n        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));\n        try\n        {\n            return await GetUserAsync(id, cts.Token);\n        }\n        catch (OperationCanceledException)\n        {\n            Console.WriteLine("Request timed out");\n            return null;\n        }\n    }\n}',
     lang:'csharp',
     keyPoints:['async Task<T> method returns future result','await pauses method without blocking thread','Task.WhenAll chạy nhiều async operations concurrent'],
     exercise:'Xây async HTTP client với retry, timeout, cancellation.'},

    {id:'aspnet',title:'ASP.NET Core Web API',
     theory:'<p><strong>ASP.NET Core</strong> framework web mạnh nhất .NET. Minimal API hoặc Controllers. Dependency Injection built-in. Middleware pipeline.</p>',
     code:'// Minimal API (ASP.NET Core 8)\nvar builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddScoped<IProductService, ProductService>();\n\nvar app = builder.Build();\n\n// Endpoints\napp.MapGet("/api/products", async (IProductService svc) =>\n    Results.Ok(await svc.GetAllAsync()));\n\napp.MapGet("/api/products/{id}", async (int id, IProductService svc) =>\n{\n    var product = await svc.GetByIdAsync(id);\n    return product is null ? Results.NotFound() : Results.Ok(product);\n});\n\napp.MapPost("/api/products", async (CreateProductDto dto, IProductService svc) =>\n{\n    var product = await svc.CreateAsync(dto);\n    return Results.Created($"/api/products/{product.Id}", product);\n})\n.WithValidation<CreateProductDto>();\n\napp.MapDelete("/api/products/{id}", async (int id, IProductService svc) =>\n{\n    await svc.DeleteAsync(id);\n    return Results.NoContent();\n});\n\napp.Run();\n\n// DTOs\npublic record CreateProductDto(string Name, decimal Price);\npublic record ProductDto(int Id, string Name, decimal Price);',
     lang:'csharp',
     keyPoints:['Minimal API: MapGet/MapPost cho route handlers ngắn gọn','Dependency Injection built-in: AddScoped/AddTransient/AddSingleton','Results.Ok/NotFound/Created cho proper HTTP responses'],
     exercise:'Xây RESTful API hoàn chỉnh với CRUD, validation, error handling.'},

    {id:'generics-advanced',title:'Advanced Generics & Patterns',
     theory:'<p>C# generics với constraints: <code>where T : class</code>, <code>where T : IComparable<T></code>. Covariance/Contravariance. Nullable reference types. Pattern matching nâng cao.</p>',
     code:'// Generic with multiple constraints\npublic class Repository<TEntity, TKey>\n    where TEntity : class, IEntity<TKey>\n    where TKey : IEquatable<TKey>\n{\n    private readonly DbContext _db;\n\n    public async Task<TEntity?> FindAsync(TKey id)\n        => await _db.Set<TEntity>().FindAsync(id);\n\n    public async Task<List<TEntity>> WhereAsync(\n        Expression<Func<TEntity, bool>> predicate)\n        => await _db.Set<TEntity>().Where(predicate).ToListAsync();\n}\n\n// Advanced pattern matching\npublic static decimal CalculateShipping(Order order) => order switch\n{\n    { Total: > 100 } => 0,              // free shipping\n    { Items.Count: > 5 } => 5.99m,      // bulk rate\n    { Address.Country: "VN" } => 2.99m, // domestic\n    { Weight: < 1 } => 4.99m,           // lightweight\n    _ => 9.99m                          // standard\n};\n\n// Result pattern (no exceptions for expected failures)\npublic record Result<T>\n{\n    public bool IsSuccess { get; init; }\n    public T? Value { get; init; }\n    public string? Error { get; init; }\n\n    public static Result<T> Ok(T value) => new() { IsSuccess = true, Value = value };\n    public static Result<T> Fail(string error) => new() { IsSuccess = false, Error = error };\n}',
     lang:'csharp',
     keyPoints:['where constraints: class, struct, new(), interface','Property pattern matching: { Prop: value } trong switch','Result<T> pattern thay exceptions cho expected failures'],
     exercise:'Implement generic Result<T> pattern cho API error handling.'}
  ]},

  {id:'mid',name:'Mid-Level',badge:'mid',desc:'EF Core, DI & Architecture',lessons:[
    {id:'ef-core',title:'Entity Framework Core',
     theory:'<p><strong>EF Core</strong> ORM cho .NET. Code-First: define C# classes → generate database. Migrations, relationships, query optimization.</p>',
     code:'// Models\npublic class Blog\n{\n    public int Id { get; set; }\n    public string Title { get; set; } = "";\n    public string Url { get; set; } = "";\n    public List<Post> Posts { get; set; } = new();\n}\n\npublic class Post\n{\n    public int Id { get; set; }\n    public string Title { get; set; } = "";\n    public string Content { get; set; } = "";\n    public int BlogId { get; set; }\n    public Blog Blog { get; set; } = null!;\n    public List<Tag> Tags { get; set; } = new();\n}\n\n// DbContext\npublic class AppDbContext : DbContext\n{\n    public DbSet<Blog> Blogs => Set<Blog>();\n    public DbSet<Post> Posts => Set<Post>();\n\n    protected override void OnModelCreating(ModelBuilder mb)\n    {\n        mb.Entity<Blog>()\n          .HasMany(b => b.Posts)\n          .WithOne(p => p.Blog)\n          .HasForeignKey(p => p.BlogId);\n    }\n}\n\n// Usage\nvar posts = await context.Posts\n    .Where(p => p.Blog.Title.Contains("Tech"))\n    .Include(p => p.Tags)\n    .OrderByDescending(p => p.Id)\n    .Take(10)\n    .ToListAsync();',
     lang:'csharp',
     keyPoints:['Code-First: C# classes → database schema via migrations','Include() cho eager loading relationships (avoid N+1)','DbSet<T> cho CRUD operations với LINQ queries'],
     exercise:'Xây blog API với EF Core: posts, comments, tags, users.'},

    {id:'di-patterns',title:'Dependency Injection & Clean Architecture',
     theory:'<p>.NET DI container built-in. <strong>Clean Architecture</strong>: Domain → Application → Infrastructure → Presentation. CQRS pattern. MediatR cho decoupling.</p>',
     code:'// Clean Architecture layers\n\n// Domain (no dependencies)\npublic interface IOrderRepository\n{\n    Task<Order?> GetByIdAsync(int id);\n    Task<Order> CreateAsync(Order order);\n}\n\n// Application (depends on Domain)\npublic class CreateOrderCommand : IRequest<OrderDto>\n{\n    public string CustomerName { get; init; } = "";\n    public List<OrderItemDto> Items { get; init; } = new();\n}\n\npublic class CreateOrderHandler : IRequestHandler<CreateOrderCommand, OrderDto>\n{\n    private readonly IOrderRepository _repo;\n    private readonly INotificationService _notifier;\n\n    public CreateOrderHandler(IOrderRepository repo, INotificationService notifier)\n    {\n        _repo = repo;\n        _notifier = notifier;\n    }\n\n    public async Task<OrderDto> Handle(CreateOrderCommand cmd, CancellationToken ct)\n    {\n        var order = Order.Create(cmd.CustomerName, cmd.Items);\n        await _repo.CreateAsync(order);\n        await _notifier.SendAsync($"New order: {order.Id}");\n        return order.ToDto();\n    }\n}\n\n// DI Registration\nbuilder.Services.AddScoped<IOrderRepository, SqlOrderRepository>();\nbuilder.Services.AddScoped<INotificationService, EmailNotifier>();\nbuilder.Services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(typeof(Program).Assembly));',
     lang:'csharp',
     keyPoints:['Clean Architecture: Domain layer không phụ thuộc anything','MediatR: CQRS pattern, decouple command từ handler','DI Lifetimes: Transient, Scoped (per-request), Singleton'],
     exercise:'Refactor monolith API sang Clean Architecture.'},

    {id:'middleware',title:'Middleware, Filters & Error Handling',
     theory:'<p>ASP.NET Core <strong>middleware pipeline</strong>: request → middleware chain → endpoint → response. Exception handling, logging, CORS, authentication. Global error handling.</p>',
     code:'// Custom middleware\npublic class RequestTimingMiddleware\n{\n    private readonly RequestDelegate _next;\n    private readonly ILogger<RequestTimingMiddleware> _logger;\n\n    public RequestTimingMiddleware(RequestDelegate next, ILogger<RequestTimingMiddleware> logger)\n    {\n        _next = next;\n        _logger = logger;\n    }\n\n    public async Task InvokeAsync(HttpContext context)\n    {\n        var sw = Stopwatch.StartNew();\n        try\n        {\n            await _next(context);\n        }\n        finally\n        {\n            sw.Stop();\n            _logger.LogInformation(\n                "{Method} {Path} responded {Status} in {Ms}ms",\n                context.Request.Method,\n                context.Request.Path,\n                context.Response.StatusCode,\n                sw.ElapsedMilliseconds);\n        }\n    }\n}\n\n// Global error handler\napp.UseExceptionHandler(error => error.Run(async context =>\n{\n    context.Response.StatusCode = 500;\n    context.Response.ContentType = "application/json";\n    var ex = context.Features.Get<IExceptionHandlerFeature>()?.Error;\n    await context.Response.WriteAsJsonAsync(new\n    {\n        error = "Internal Server Error",\n        message = app.Environment.IsDevelopment() ? ex?.Message : "An error occurred"\n    });\n}));\n\napp.UseMiddleware<RequestTimingMiddleware>();',
     lang:'csharp',
     keyPoints:['Middleware chain: order matters (auth before endpoints)','RequestDelegate _next cho pipeline forwarding','Global exception handler cho consistent error responses'],
     exercise:'Xây middleware: rate limiting, request logging, JWT auth.'}
  ]},

  {id:'senior',name:'Senior',badge:'senior',desc:'Performance & Advanced .NET',lessons:[
    {id:'performance',title:'Performance Optimization',
     theory:'<p>C# performance: <code>Span<T></code> cho zero-allocation slicing, <code>ValueTask</code> cho hot-path async, <code>ArrayPool</code> giảm GC pressure. Benchmarking với BenchmarkDotNet.</p>',
     code:'using System.Buffers;\nusing BenchmarkDotNet.Attributes;\n\npublic class PerformanceBenchmarks\n{\n    // Span<T> - zero copy slicing\n    public static int SumWithSpan(ReadOnlySpan<int> numbers)\n    {\n        int sum = 0;\n        foreach (var n in numbers) sum += n;\n        return sum;\n    }\n\n    // ArrayPool - reuse arrays (no GC)\n    public static byte[] ProcessData(int size)\n    {\n        var pool = ArrayPool<byte>.Shared;\n        var buffer = pool.Rent(size);\n        try\n        {\n            // Process buffer...\n            return buffer[..size].ToArray();\n        }\n        finally\n        {\n            pool.Return(buffer);\n        }\n    }\n\n    // ValueTask for hot path\n    private readonly Dictionary<int, User> _cache = new();\n\n    public ValueTask<User> GetUserAsync(int id)\n    {\n        if (_cache.TryGetValue(id, out var user))\n            return ValueTask.FromResult(user); // no allocation!\n\n        return new ValueTask<User>(LoadFromDbAsync(id));\n    }\n\n    // Benchmark\n    [Benchmark]\n    public void SpanBenchmark()\n    {\n        int[] data = Enumerable.Range(0, 1000).ToArray();\n        SumWithSpan(data.AsSpan());\n    }\n}',
     lang:'csharp',
     keyPoints:['Span<T>: stack-allocated view, zero-copy string/array operations','ValueTask: avoid Task allocation cho cached/sync paths','ArrayPool: rent/return arrays thay new/GC'],
     exercise:'Optimize hot path: giảm allocations 80% dùng Span + pools.'},

    {id:'dotnet-advanced',title:'Advanced .NET Features',
     theory:'<p>Source generators tạo code tại compile time. Native AOT compilation. gRPC cho high-performance RPC. SignalR cho real-time. .NET 8 features.</p>',
     code:'// Source Generator (simplified)\n[JsonSerializable(typeof(User))]\n[JsonSerializable(typeof(List<User>))]\npublic partial class AppJsonContext : JsonSerializerContext { }\n\n// Usage: zero-reflection serialization\nvar json = JsonSerializer.Serialize(user, AppJsonContext.Default.User);\n\n// gRPC service\npublic class GreeterService : Greeter.GreeterBase\n{\n    public override Task<HelloReply> SayHello(\n        HelloRequest request, ServerCallContext context)\n    {\n        return Task.FromResult(new HelloReply\n        {\n            Message = $"Hello {request.Name}"\n        });\n    }\n}\n\n// SignalR Hub (real-time)\npublic class ChatHub : Hub\n{\n    public async Task SendMessage(string user, string message)\n    {\n        await Clients.All.SendAsync("ReceiveMessage", user, message);\n    }\n\n    public async Task JoinRoom(string room)\n    {\n        await Groups.AddToGroupAsync(Context.ConnectionId, room);\n        await Clients.Group(room).SendAsync("UserJoined", Context.User?.Identity?.Name);\n    }\n}',
     lang:'csharp',
     keyPoints:['Source generators: compile-time code generation, zero reflection','Native AOT: ahead-of-time compile → instant startup','SignalR: real-time WebSocket communication'],
     exercise:'Xây real-time chat app với SignalR + authentication.'}
  ]},

  {id:'master',name:'Master',badge:'master',desc:'Architecture & System Design',lessons:[
    {id:'architecture',title:'.NET System Design & Architecture',
     theory:'<p>Microservices với .NET Aspire. Event-driven architecture. Domain-Driven Design (DDD). CQRS + Event Sourcing. Distributed caching, message queues.</p>',
     code:'// Domain-Driven Design\npublic abstract class AggregateRoot\n{\n    private readonly List<IDomainEvent> _events = new();\n    public IReadOnlyList<IDomainEvent> DomainEvents => _events;\n    protected void AddEvent(IDomainEvent e) => _events.Add(e);\n    public void ClearEvents() => _events.Clear();\n}\n\npublic class Order : AggregateRoot\n{\n    public OrderId Id { get; }\n    public OrderStatus Status { get; private set; }\n    private readonly List<OrderItem> _items = new();\n\n    public static Order Create(CustomerId customerId)\n    {\n        var order = new Order(OrderId.New(), customerId);\n        order.AddEvent(new OrderCreatedEvent(order.Id));\n        return order;\n    }\n\n    public void AddItem(ProductId product, int qty, Money price)\n    {\n        if (Status != OrderStatus.Draft)\n            throw new DomainException("Cannot add items to confirmed order");\n        _items.Add(new OrderItem(product, qty, price));\n    }\n\n    public void Confirm()\n    {\n        if (!_items.Any()) throw new DomainException("Empty order");\n        Status = OrderStatus.Confirmed;\n        AddEvent(new OrderConfirmedEvent(Id, Total));\n    }\n\n    public Money Total => _items.Sum(i => i.Price * i.Quantity);\n}\n\n// Strongly typed IDs\npublic record OrderId(Guid Value) { public static OrderId New() => new(Guid.NewGuid()); }',
     lang:'csharp',
     keyPoints:['DDD: AggregateRoot, Value Objects, Domain Events','Strongly typed IDs prevent mixing different entity IDs','Event Sourcing: store events, rebuild state from event stream'],
     exercise:'Implement DDD e-commerce: Order aggregate, domain events, CQRS.'}
  ]}
]
};
